### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by dos1** [panzi/Browser-Ponies#3]
Browser Ponies lacks any license information (or I'm blind...)

This is major issue, as now I don't know neither if I can use Browser Ponies in my project, nor how and if I can contribute to BP.

Even if this information is somewhere accessible, it still should be available right from projects main page and from distribution package (and preferably also in source files).

**Comment by panzi** [comment]
Yeah, I should add some license. What license would you prefer? I'm open to anything ranging from LGPL to MIT. However, the resources (GIFs, Pony.inis and sound files) aren't done by me. They are from the Desktop Pony project. I think the images and INIs are under some CC license, but it might vary from pony to pony. See: http://desktop-pony-team.deviantart.com/ (but I'm not sure if all ponies come from there - the Desktop Ponies "web page" changes constantly) The sound files are taken from the show, so they are copyrighted by Hasbro. Even though I'm not from the USA I hope this usage here is covered by fair use (which only exists in the USA).

So I can only apply a license to my code (JavaScript and HTML). Would that be enough for you?

**Comment by dos1** [comment]
Actually, every free license should be fine for me - and it's your code, so it's your choice ;)

Yes, I'm aware that ponies are not made by you, it's pretty clear from the website. It was the code I was talking about, so yes, that would be enough :)

**Comment by maandree** [comment]
I think you should use their GPL or LGPL, personally I would prefer GPLv3 because it fights for user freedom more.

Regardless of which license you choose, do not forget to tag it in a LibreJS parsable manner.

**Comment by panzi** [comment]
I choose MIT. I'm not sure if GPL would even be a possible license for a bookmarklet/widget, because depending on how you interpret it, it'll link against code that is not under a compatible license (the rest of the webpage). I could have chosen LGPL, but actually I don't care enough.
