### ISSUE TITLE
Add latest ponies from Desktop Ponies

### ISSUE THREAD

**Issue by RoosterDragon** [panzi/Browser-Ponies#8]
Hi there. Desktop Ponies just reached 200 ponies and I was hoping you might add the new ones see the web can enjoy their presence too.

You can find the assets [here](https://github.com/RoosterDragon/Desktop-Ponies/tree/master/Content/Ponies).

**Comment by panzi** [comment]
I'll take a look at it next weekend.

**Comment by panzi** [comment]
Done.
