### ISSUE TITLE
Bookmarklet does not work on HTTPS sites

### ISSUE THREAD

**Issue by Sequoia** [panzi/Browser-Ponies#9]
## Reproduction
1. Install bookmarklet (drag to toolbar)
2. navigate to https://google.com
3. click bookmarklet
## Expected

ponies
# Actual

No ponies

```
[blocked] The page at 'https://www.google.com/?gws_rd=ssl' was loaded over HTTPS, but ran insecure content from 'http://panzi.github.io/Browser-Ponies/browserponies.js': this content should also be loaded over HTTPS.
```

**Comment by Sequoia** [comment]
Make all urls HTTPS in the marklet & throughout the codebase should do it I believe. http://civic.mit.edu/blog/elplatt/http-must-die

**Comment by panzi** [comment]
Ah yes. I never updated that code once I moved to a hoster that provides https. Will fix that (maybe today, maybe next weekend).

**Comment by panzi** [comment]
Ok, done.
